module.exports = {
    data: {
        "22E8i_T_-C1~180eeb80-1bd0-009a-3f4a-00155dae811f": {
            nodes: [
                {
                    key: 1,
                    question: "我想了解所有的紓困振興方案",
                    description: "所有關於紓困振興方案的解決方案",
                    FChannel: "web",
                    FModuleType: "DEFAULT",
                    FNodeType: "start",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["card", "text", "card", "image", "text", "qaReply"],
                },
                {
                    key: 2,
                    question: "我想知道企業的方案",
                    description: "所有關於企業的解決方案",
                    FChannel: "line",
                    FModuleType: "ACTIVITY",
                    FNodeType: "genernal",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["text", "text", "qaReply"],
                },
                {
                    key: 3,
                    question: "想知道企業有關的紓困資訊",
                    description: "所有關於企業有關的紓困資訊與解決方案",
                    FChannel: "web",
                    FModuleType: "ACTIVITY",
                    FNodeType: "genernal",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["video", "text", "image", "text", "qaReply"],
                },
                {
                    key: 4,
                    question: "可以專人服務嗎",
                    description: "所有關於專人服務的電話號碼",
                    FChannel: "line",
                    FModuleType: "DEFAULT",
                    FNodeType: "genernal",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["mediaCard", "text", "text", "qaReply"],
                },
                {
                    key: 5,
                    question: "我不確定我的行業別是否符合紓困",
                    description: "所有關於各種行業別是否符合紓困的資訊與解決方案",
                    FChannel: "line",
                    FModuleType: "ACTIVITY",
                    FNodeType: "end",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["text", "text", "qaReply"],
                },
                {
                    key: 6,
                    question: "請問美甲業及食品業可以補助嗎",
                    description: "所有關於美甲業及食品業的資訊與解決方案",
                    FChannel: "web",
                    FModuleType: "ACTIVITY",
                    FNodeType: "end",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["video", "text", "image", "text", "qaReply"],
                },
                {
                    key: 7,
                    question: "請問商業服務業薪資及營運資金補貼會怎麼支付",
                    description: "所有關於請問商業服務業薪資及營運資金補貼的資訊",
                    FChannel: "web",
                    FModuleType: "DEFAULT",
                    FNodeType: "end",
                    FNode: "next",
                    FNodeNextKey: "22E8i_T_-C1~180eeb80-1bd0-009a-3f4a-00155dae1234",
                    FAnswerType: ["card", "text", "card", "image", "text", "qaReply"],
                },
            ],
            connections: [
                { from: 1, to: 2, ffaType: "mediaCard" },
                { from: 1, to: 3, ffaType: "card" },
                { from: 1, to: 4, ffaType: "qaReply" },
                { from: 2, to: 5, ffaType: "mediaCard" },
                { from: 4, to: 6, ffaType: "qaReply" },
                { from: 4, to: 7, ffaType: "qaReply" },
            ],
        },
        "22E8i_T_-C1~180eeb80-1bd0-009a-3f4a-00155dae1234": {
            nodes: [
                {
                    key: 1,
                    question: "我想了解所有的紓困振興方案",
                    description: "所有關於紓困振興方案的解決方案",
                    FChannel: "line",
                    FModuleType: "DEFAULT",
                    FNodeType: "start",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["mediaCard", "text", "text", "qaReply"],
                },
                {
                    key: 2,
                    question: "我想知道企業的方案",
                    description: "所有關於企業的解決方案",
                    FChannel: "line",
                    FModuleType: "ACTIVITY",
                    FNodeType: "genernal",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["text", "text", "qaReply"],
                },
                {
                    key: 3,
                    question: "想知道企業有關的紓困資訊",
                    description: "所有關於企業有關的紓困資訊與解決方案",
                    FChannel: "web",
                    FModuleType: "ACTIVITY",
                    FNodeType: "genernal",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["video", "text", "image", "text", "qaReply"],
                },
                {
                    key: 4,
                    question: "可以專人服務嗎",
                    description: "所有關於專人服務的電話號碼",
                    FChannel: "line",
                    FModuleType: "DEFAULT",
                    FNodeType: "genernal",
                    FNode: "node",
                    FNodeNextKey: "",
                    FAnswerType: ["mediaCard", "text", "text", "qaReply"],
                },
            ],
            connections: [
                { from: 1, to: 2, ffaType: "mediaCard" },
                { from: 1, to: 3, ffaType: "card" },
                { from: 1, to: 4, ffaType: "qaReply" },
            ],
        },
    },
    _header_: {
        success: true,
        timeCost: 865,
    },
    resultInfo: {
        success: true,
    },
};
