module.exports = {
    pageCount: 1,
    _header_: {
        success: true,
        timeCost: 47,
    },
    hasNextPage: false,
    recordCount: 4,
    items: [
        {
            FId: "00000000-0000-0000-1001-000000000001",
            FAdminQty: 1,
            FEnabled: true,
            FPhone: "",
            FFullName: "集團",
            FContactPhone: "",
            FUserId: "00000000-0000-0000-1002-000000000001",
            FUnifyId: "",
            Fowner: "",
            FAddress: "",
            FContactAddress: "",
            FName: "集團",
            FIdentityCardNumber: "",
            FTreeSerial: "001",
            FOtherRoleQty: 4,
            FTenantQuantity: 1,
            FIdentityCardNumberType: "",
            FUserId$: "系統管理員",
        },
        {
            FId: "1795922a-0500-0a73-572f-90784189a4c2",
            FAdminQty: 1,
            FEnabled: true,
            FPhone: "0966666666",
            FContactPhone: "",
            FUserId: "00000000-0000-0000-1002-000000000001",
            FUnifyId: "Bryant-統編",
            Fowner: "Bryant",
            FAddress: "公司登記地址",
            FContactAddress: "",
            FName: "Bryant Company",
            FIdentityCardNumber: "ID",
            FTreeSerial: "002",
            FOtherRoleQty: 6,
            FTenantQuantity: 2,
            FIdentityCardNumberType: "",
            FUserId$: "系統管理員",
        },
        {
            FId: "179a74dd-f280-0a58-5074-00090faa0001",
            FAdminQty: 1,
            FEnabled: true,
            FPhone: "TEST",
            FContactPhone: "",
            FUserId: "00000000-0000-0000-1002-000000000001",
            FUnifyId: "TEST",
            Fowner: "TEST",
            FAddress: "TEST",
            FContactAddress: "",
            FName: "TEST",
            FIdentityCardNumber: "TEST",
            FTreeSerial: "003",
            FOtherRoleQty: 4,
            FTenantQuantity: 0,
            FIdentityCardNumberType: "",
            FUserId$: "系統管理員",
        },
        {
            FId: "179a7cca-74b0-0a58-5074-00090faa0001",
            FAdminQty: 1,
            FEnabled: true,
            FPhone: "Bryant_Tes",
            FContactPhone: "",
            FUserId: "00000000-0000-0000-1002-000000000001",
            FUnifyId: "Bryant_Tes",
            Fowner: "Bryant_Test",
            FAddress: "Bryant_Test",
            FContactAddress: "",
            FName: "Bryant_Test",
            FIdentityCardNumber: "",
            FTreeSerial: "004",
            FOtherRoleQty: 4,
            FTenantQuantity: 0,
            FIdentityCardNumberType: "",
            FUserId$: "系統管理員",
        },
    ],
};
