module.exports = {
    _header_: {
        success: true,
        timeCost: 13,
    },
    hasNextPage: false,
    items: [
        {
            FId: "a081e20b-05e1-41d0-bdec-e5e13a78fd65",
            FOAuthResponseType: "code",
            FOAuthScope: "profile%20openid",
            FTenantId: "17d9e267-d0f0-07af-6fd2-00155d3ebbad",
            FIdentifyBy: "FLineId",
            FChannel: "line",
            FOAuthClientSecret: "6c3bc36d-5821-4a03-b308-08f487bdc9ee",
            FShowChannel: "LINE",
            FContactName: "name",
            FOAuthAnswerEnable: true,
            FTenantId$: "languageTest",
            FName: "",
            FIdentifyValue: "sub",
            FChannel$: "LINE",
            FPassType$: "混合模式",
            FPassType: "both",
            FOAuthAuthorizeUrl: "https://access.line.me/oauth2/v2.1/authorize",
            FOAuthGrantType: "authorization_code",
            FOAuthIndex: 1,
            FOAuthTokenUrl: "https://api.line.me/oauth2/v2.1/token",
            FOAuthClientId: "58613fa1-6ccc-4e1a-9400-87fd31e03c61",
        },
        {
            FId: "a081e20b-05e1-41d0-bdec-e5e13a78fd63",
            FOAuthResponseType: "code",
            FOAuthScope: "profile%20openid",
            FTenantId: "17d9e267-d0f0-07af-6fd2-00155d3ebbad",
            FIdentifyBy: "FLineId",
            FChannel: "microsoft",
            FOAuthClientSecret: "6c3bc36d-5821-4a03-b308-08f487bdc9ee",
            FShowChannel: "Microsoft",
            FContactName: "name",
            FOAuthAnswerEnable: false,
            FTenantId$: "languageTest",
            FName: "",
            FIdentifyValue: "sub",
            FChannel$: "Microsoft",
            FPassType$: "混合模式",
            FPassType: "both",
            FOAuthAuthorizeUrl: "https://access.microsoft.me/oauth2/v2.1/authorize",
            FOAuthGrantType: "authorization_code",
            FOAuthIndex: 2,
            FOAuthTokenUrl: "https://api.microsoft.me/oauth2/v2.1/token",
            FOAuthClientId: "58613fa1-6ccc-4e1a-9400-87fd31e03c61",
        },
        {
            FId: "a081e20b-05e1-41d0-bdec-e5e13a78fd63",
            FOAuthResponseType: "code",
            FOAuthScope: "profile%20openid",
            FTenantId: "17d9e267-d0f0-07af-6fd2-00155d3ebbad",
            FIdentifyBy: "FLineId",
            FChannel: "google",
            FOAuthClientSecret: "6c3bc36d-5821-4a03-b308-08f487bdc9ee",
            FShowChannel: "Google",
            FContactName: "name",
            FOAuthAnswerEnable: true,
            FTenantId$: "languageTest",
            FName: "",
            FIdentifyValue: "sub",
            FChannel$: "google",
            FPassType$: "混合模式",
            FPassType: "both",
            FOAuthAuthorizeUrl: "https://access.google.me/oauth2/v2.1/authorize",
            FOAuthGrantType: "authorization_code",
            FOAuthIndex: 3,
            FOAuthTokenUrl: "https://api.google.me/oauth2/v2.1/token",
            FOAuthClientId: "58613fa1-6ccc-4e1a-9400-87fd31e03c61",
        },
    ],
};
